# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-18 08:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('music', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='song',
            name='file',
            field=models.FileField(default=1, upload_to=''),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='album',
            name='a_logo',
            field=models.FileField(upload_to=''),
        ),
    ]
